### ISSUE TITLE
need to bump setup.py version #

### ISSUE THREAD

**Issue by synman** [bbernhard/OctoPrint-Signalclirestapi#10]
Awesome to see the new release out... setup.py needs the new version # for it work though.   Folks are likely getting repeated prompts to upgrade with it as is.

https://github.com/bbernhard/OctoPrint-Signalclirestapi/blob/master/setup.py#L17

**Comment by 6ffm70** [comment]
^this. I removed the old one, then removed it completely... still installs 0.1.1
```
Installing plugin "Signalclirestapi" from https://github.com/bbernhard/OctoPrint-Signalclirestapi/archive/master.zip...
/home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmpuexn1bid/OctoPrint-Signalclirestapi-master.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpuexn1bid/OctoPrint-Signalclirestapi-master.zip
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python3.7/site-packages (from Signal-Notifications==0.1.1) (1.8.6)
Requirement already satisfied: pysignalclirestapi==0.3.15 in /home/pi/oprint/lib/python3.7/site-packages (from Signal-Notifications==0.1.1) (0.3.15)
Requirement already satisfied: sentry-sdk<2,>=1.5.7 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->Signal-Notifications==0.1.1) (1.11.0)
```
snip
```
Successfully built Signal-Notifications
Installing collected packages: Signal-Notifications
Successfully installed Signal-Notifications-0.1.1
Done!
```

**Comment by synman** [comment]
yeah, it'll just keep prompting to upgrade again until the version signature in setup.py matches the tag name.

**Comment by bbernhard** [comment]
Sorry, completely forgot to bump the version in the `setup.py` file, but should now be fixed! Thanks for bringing this to my attention!

**Comment by 6ffm70** [comment]
still returns this after oprint restart and hitting update:
```
Installing collected packages: Signal-Notifications
Successfully installed Signal-Notifications-0.1.1
The update finished successfully and the server will now be restarted.
```

**Comment by bbernhard** [comment]
That's strange. According to the [Octoprint plugin site](https://plugins.octoprint.org/plugins/signalclirestapi/), the `master` branch is used (https://github.com/bbernhard/OctoPrint-Signalclirestapi/archive/master.zip) which should contain the right version. :thinking:

**Comment by bbernhard** [comment]
I created another release (`0.2.1`), as I wasn't sure what Octoprint actually uses. If it is the latest released version or the master branch. Can you please try again? :)

**Comment by synman** [comment]
it may be the release tag.   you'll need to delete it and recreate it with your commit including the updated setup.py if not already done.

**Comment by synman** [comment]
yeah, that's what it was:  https://github.com/bbernhard/OctoPrint-Signalclirestapi/blob/0.2.0/setup.py

creating a new release should be just as good.

should be good to go now with 0.2.1:  https://github.com/bbernhard/OctoPrint-Signalclirestapi/blob/0.2.1/setup.py

**Comment by synman** [comment]
will force an additional install for everyone but the update loop will settle down soon after

**Comment by 6ffm70** [comment]
Looking good:
```
Found existing installation: Signal-Notifications 0.1.1
Uninstalling Signal-Notifications-0.1.1:
Successfully uninstalled Signal-Notifications-0.1.1
Successfully installed Signal-Notifications-0.2.1
The update finished successfully and the server will now be restarted.
```

**Comment by 6ffm70** [comment]
Yes, that did the trick! Thank you both
