### ISSUE TITLE
[Feature] Add notification option for filament change

### ISSUE THREAD

**Issue by 6ffm70** [bbernhard/OctoPrint-Signalclirestapi#3]
When printing a job with two or more different filaments, Prusa printers will pause for manual filament changes with gcode M600.

It would be great to get a Signal notification when not in the same room as the printer. I could imagine a new event in this very plugin to tick a box at.

The event for this in Octoprint has been created and merged into the upcoming 1.7.0 release:
https://github.com/OctoPrint/OctoPrint/pull/4187

Thanks for providing this plugin @bbernhard !

**Comment by bbernhard** [comment]
Octoprint v1.7.0 seems to be released now. I'll have a look at it in the next days.

**Comment by bbernhard** [comment]
Many thanks, I've added a comment to your PR!

btw: Not sure if you are already aware, but the latest `signal-cli-rest-api` version now supports the `JSON-RPC` mode, which is way faster than the normal/native mode. Especially for things like filament change notifications, that might be useful (as you will receive the notifications faster) :)

**Comment by 6ffm70** [comment]
Works as expected!
