### ISSUE TITLE
This plugin has a ton of potential

### ISSUE THREAD

**Issue by synman** [bbernhard/OctoPrint-Signalclirestapi#7]
Will you accept PRs?   I have some things I'm working on in my fork that I'd be more than happy to share if you accept PRs.

- Group by machine/printer - maintain a persistent group using the printer profile name (printer / machine farm)
- User defined status update intervals (basically a tuple and in clause for when to send updates)
- Request current status - filters by group / machine / job
- Cancel current job - filters by group / machine / job

**Comment by bbernhard** [comment]
sure. would love to integrate your changes!

**Comment by synman** [comment]
I've got send / receive wrapped up for a single client / single number use case.  I imagine it would work fine for a multi-client / multi number use case as well.

The use case that has me stumped, and of course it is my own, is the multi-client / single number one.  

I have 4 machines deployed using a single signal # talking to a single instance of signal-cli (your container actually).   Using json-rpc, I'm able to spin up a web socket for receive for each client but (same goes for normal mode with the /v1/receive GET) messages are received in a FIFO manner.  Once a client receives a message, it is no longer on the stack for others.

Is it possible with json-rpc mode to iterate thru all connected web sockets and basically "broadcast" the messages to all connected clients rather than the current FIFO type approach?  I haven't looked at the actual code yet, but this would be an ideal state for my situation.

I'm also going to take a look at running multiple containers with the same account.  I imagine since each one is treated like a device, I'll be able to slice it that way too.

I definitely like the json-rpc implementation.   normal was taxing my Synology DS1621+ with 4 active clients each calling receive once per second.

One last note, mainly for posterity as I would be very hesitant to release this, I did come up with some mitigating logic to allow this multi-client / single number use case to partially work.  If anything, you'll probably get a chuckle out of it:

```
                    # we only want to respond to messages meant for us
                    if not groupId is None and groupId == _plugin._group_id["internal_id"]:
                        _plugin._logger.debug("signal_receive_thread: message=[{}] group=[{}]".format(message, groupId))   
                        if message.strip().upper() == "STATUS":
                            _plugin.on_print_progress("dummy", _plugin._last_filename, _plugin._last_progress, override=True)
                        elif message.strip().upper() == "CANCEL":
                            _plugin._printer.cancel_print()
                        elif message.strip().upper() == "SHUTDOWN":
                            cmd = _plugin._settings.global_get(["server", "commands", "systemShutdownCommand"])
                            subprocess.call(cmd, shell=True)
                        elif message.strip().upper() == "REBOOT":
                            cmd = _plugin._settings.global_get(["server", "commands", "systemRestartCommand"])
                            subprocess.call(cmd, shell=True)
                    elif not groupId is None:
                        for group in groups:
                            if group["internal_id"] == groupId:
                                _plugin._logger.debug("signal_receive_thread: rejecting message=[{}] group=[{}]".format(message, group["id"]))   
                                send_message(_plugin.url, _plugin.sender, "Try again", [group["id"]])
                                time.sleep(44)                                    
                                break
```
I put each client's receive loop to sleep for 45 seconds if it receives a message meant for another instance :)

<img width="894" alt="Screenshot 2023-01-16 at 11 25 03 AM" src="https://user-images.githubusercontent.com/1299716/212725300-883582a0-eccf-4314-a378-59908eb2984a.png">

**Comment by synman** [comment]
closing this as PR has been opened

https://github.com/bbernhard/OctoPrint-Signalclirestapi/pull/8
